In [2]:
import tensorflow as tf
import pandas as pd
from tensorflow.keras import layers
from sklearn.datasets import load_iris
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
# load data
data = load_iris()
df = pd.DataFrame(data.data)

size = int(0.75*len(df))
x_train = df.iloc[: size, :-1]
y_train = df.iloc[: size, -1]
x_test = df.iloc[size: , :-1]
y_test = df.iloc[size: , -1]
# Convert data to TensorFlow tensors
x_train = tf.convert_to_tensor(x_train)
y_train = tf.convert_to_tensor(y_train)
x_test = tf.convert_to_tensor(x_test)
y_test = tf.convert_to_tensor(y_test)
dropout_rate = 0.2
model = tf.keras.Sequential([
        layers.Dense(4, activation='relu'),
        layers.Dropout(dropout_rate),
        layers.Dense(10, activation='relu'),
        layers.Dense(10, activation='softmax')
    ])

model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout (Dropout)                    │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [3]:
model.compile(optimizer='SGD', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
d = model.fit(x_train, y_train, epochs=10, validation_data = (x_test, y_test))

Epoch 1/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 83ms/step - accuracy: 0.0186 - loss: 2.7374 - val_accuracy: 0.1316 - val_loss: 1.5509
Epoch 2/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.0088 - loss: 2.2025 - val_accuracy: 0.0000e+00 - val_loss: 1.6293
Epoch 3/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.0683 - loss: 1.9481 - val_accuracy: 0.0000e+00 - val_loss: 1.7375
Epoch 4/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.0746 - loss: 1.7221 - val_accuracy: 0.0000e+00 - val_loss: 1.8180
Epoch 5/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.0506 - loss: 1.6489 - val_accuracy: 0.0000e+00 - val_loss: 1.9395
Epoch 6/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.0646 - loss: 1.5220 - val_accuracy: 0.0000e+00 - val_loss: 2.0443
Epoch 7/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.0562 - loss: 1.4419 - val_accuracy: 0.0000e+00 - val_loss: 2.1487
Epoch 8/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.0375 - loss: 1.4686 - val_accuracy: 0.

In [4]:
model.get_weights()

[array([[-0.8803406 ,  0.8049237 , -0.27700055,  0.83106446],
        [-0.21824992, -0.00571417, -0.34858245, -0.56288135],
        [-0.672449  ,  0.05355415, -0.05788869, -0.46413875]],
       dtype=float32),
 array([ 0.        ,  0.00660371,  0.        , -0.01397761], dtype=float32),
 array([[ 0.28557342,  0.65247977,  0.25583476,  0.48784673, -0.08319288,
         -0.13200837, -0.25661033, -0.6447072 ,  0.15715837, -0.27795902],
        [ 0.06186978,  0.12296596,  0.19049782, -0.6033453 ,  0.5572215 ,
         -0.08522183,  0.04691613, -0.2405901 ,  0.3759571 , -0.08100492],
        [-0.3696529 ,  0.33791196, -0.3265597 , -0.35914406,  0.65072024,
          0.6319685 ,  0.5762112 , -0.25865576, -0.07405728,  0.15179825],
        [-0.4031457 , -0.5612229 , -0.10360069, -0.5257242 , -0.21261775,
         -0.33950058,  0.6310769 , -0.24945477, -0.1407866 ,  0.4357784 ]],
       dtype=float32),
 array([-0.00680668,  0.00898723, -0.04408321,  0.        ,  0.02616845,
         0.        ,

In [5]:
test_score, test_accuracy = model.evaluate(x_test, y_test)
print(f"Test Accuracy: {test_accuracy} %")

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.0000e+00 - loss: 2.4130 
Test Accuracy: 0.0 %
